### ISSUE TITLE
Possible bugs in relative_logits functions

### ISSUE THREAD

**Issue by tqbl** [leaderj1001/Attention-Augmented-Conv2d#1]
In the `relative_logits()` function, you have
```
q = torch.transpose(q, 2, 4)
```
which gives a tensor with shape `(B, Nh, W, H, dkh)`, not `(B, Nh, H, W, dkh)`.

In the `relative_logits_1d()` function, you have
```
rel_logits = torch.einsum('bhxyd,md->bhmxy', q, rel_k)
rel_logits = torch.reshape(rel_logits, (-1, Nh * H, W, 2 * W - 1))
```
Shouldn't the einsum string be `'bhxyd,md->bhxym'`? Otherwise, you are reshaping a tensor with shape `(B, Nh, 2 * W - 1, H, W)` to a tensor with shape `(B, Nh * H, W, 2 * W - 1)` in the second line.

**Comment by leaderj1001** [comment]
Thank you for your opinion. I’ll check it as soon as possible. Thank you :)
