### ISSUE TITLE
torch.einsum() compatibility

### ISSUE THREAD

**Issue by SCoulY** [leaderj1001/Attention-Augmented-Conv2d#3]
Hi, i am testing your sample code in attention_augmented_conv.py with:
`tmp = torch.randn((16, 3, 32, 32))
    a = AugmentedConv(3, 20, kernel_size=3, dk=40, dv=4, Nh=2, relative=True)
    print(a(tmp).shape)`
But it raises:
`Traceback (most recent call last):
  File "attention_augmented_conv.py", line 131, in <module>
    print(a(tmp).shape)
  File "/Users/scouly/anaconda3/envs/Pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "attention_augmented_conv.py", line 44, in forward
    h_rel_logits, w_rel_logits = self.relative_logits(q)
  File "attention_augmented_conv.py", line 90, in relative_logits
    rel_logits_w = self.relative_logits_1d(q, key_rel_w, H, W, Nh, "w")
  File "attention_augmented_conv.py", line 99, in relative_logits_1d
    rel_logits = torch.einsum('bhxyd,md->bhxym', q, rel_k)
TypeError: einsum() takes 2 positional arguments but 3 were given`
I'm guessing if it's caused by the version compatibility issue of pytorch.
BTW i am currently using pytorch 0.4.1 on Mac OS

**Comment by QingdaChen** [comment]
We have the same problem

**Comment by leaderj1001** [comment]
I’ll check as soon as possible. I use pytorch 1.0.1 version. Additionally I will attach version requirements. Thank you :)

**Comment by leaderj1001** [comment]
When I look at the pytorch documents, I can see that 0.4.1 and 1.0.1 are slightly different. I'll leave a link.
[pytorch 1.0.1 documents](https://pytorch.org/docs/stable/torch.html)
[pytorch 0.4.1 documents](https://pytorch.org/docs/0.4.1/torch.html)
This is my guess. If you are going to use it in pytorch 0.4.1, you can change it as follows.
pytorch 0.4.1 version: torch.einsum('bhxyd,md->bhxym', (q, rel_k))

**Comment by QingdaChen** [comment]
How to change the padding of the convolution layer for example (0)?

**Comment by SCoulY** [comment]
Thanks!
