### ISSUE TITLE
How to change the padding of the convolution layer for example (0)?

### ISSUE THREAD

**Issue by QingdaChen** [leaderj1001/Attention-Augmented-Conv2d#4]

**Comment by leaderj1001** [comment]
I do not see any mention of padding in the paper. So if you want to change the padding, you can just fit the matrix shape. Thank you :)

**Comment by maxmatical** [comment]
if we change the output dimensions of the conv layers, do we have to adjust anything in the self attention layers to adjust? I'm trying to implement an attention augmented densenet (similar to your work for wide resnet), and I'm wondering how to change the augmented conv layers for downsampling

**Comment by leaderj1001** [comment]
If you want to change the out_channels, you just change a number of the out_channels. And if you want to downsampling, you can change a stride. 
Let’s assume, input_size is (32, 32, 3). If you want to get downsample output, you can change stride=2. The result is (16, 16, out_channels).
In Wide-ResNet folder, you can see the example of downsampling.
Thank you !!

**Comment by maxmatical** [comment]
So you don't need to change anything in the self attention layer? or do you have to make sure the stride/padding/kernel size for conv_out and qkv_out have to be the same?

Thanks for all your work!

**Comment by leaderj1001** [comment]
Yes ! Simply change the parameters in the "AugmentedConv". If you want to downsampling, give stride=2. And the other parameters(dk, dv, Nh) are in the README and out_channels is a minimum of 20 dimensions per head for the keys.
There will be more information about the parameters in the paper. And I'll add documentation as soon as possible.
Thank you so much for your interest :)
