### ISSUE TITLE
这里的矩阵乘法应该有问题

### ISSUE THREAD

**Issue by flystarhe** [leaderj1001/Attention-Augmented-Conv2d#6]
https://github.com/leaderj1001/Attention-Augmented-Conv2d/blob/c04acfbdd1a81f18a978fe7ccf54b0061fdc7c9f/in_paper_attention_augmented_conv/attention_augmented_conv.py#L51

正确的直觉应该是这样：
```python
attn_out = torch.matmul(flat_v, weights)
```

**Comment by luzhilin19951120** [comment]
No I don't think so, the original version matches with the paper and is logically right

**Comment by Kylin9511** [comment]
> https://github.com/leaderj1001/Attention-Augmented-Conv2d/blob/c04acfbdd1a81f18a978fe7ccf54b0061fdc7c9f/in_paper_attention_augmented_conv/attention_augmented_conv.py#L51
> 
> 正确的直觉应该是这样：
> 
> ```python
> attn_out = torch.matmul(flat_v, weights)
> ```

__No I don't think so, the original version matches with the paper and is logically right__

**Comment by leaderj1001** [comment]
Thank you for your opinion. But it is like a paper when I review it.
```
attn_out = tf.matmul(weights, flat_v)
```
weights = [batch, Nh, H * W, H * W]
flat_v = [batch, Nh, H * W, dv]
flat_v.transpose(2, 3) = [batch, Nh, H * W, dv] 
so, it is same result. Thank you.
